version: '3'
services:
  app:
    container_name: SimpleTest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: 1000
        USER_GID: 1000
    volumes:
    - /var/run/docker.sock:/var/run/docker-host.sock
    - ..:/workspaces:cached
    # - shareddata:/tmp/host
    network_mode: host
    command: sleep infinity
# volumes:
#   shareddata:
#     external: true
