version: '3'
services:
  app:
    container_name: SimpleTest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity
  db:
    container_name: SimpleTestDB
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      COLLATION: Latin1_General_CI_AS
      SA_PASSWORD: APr3ttyStr0ngP@ssword
